global:
  scrape_interval: 15s  # Scrape metrics every 15 seconds
  evaluation_interval: 15s  # Evaluate rules every 15 seconds

scrape_configs:
  # Scraping the frontend (Angular) app running on port 4200
  - job_name: 'frontend'
    static_configs:
      - targets: ['13.53.218.39:80']

  # Scraping the monitoring service running on port 9090
  - job_name: 'prometheus'
    static_configs:
      - targets: ['13.53.218.39:9090']


  # Scraping the monitoring service running on port 3000
  - job_name: 'grafana'
    static_configs:
      - targets: ['13.53.218.39:3000']


  - job_name: 'cadvisor'

    static_configs:
      - targets: ['13.53.218.39:8082']
